# Generated by Django 4.0.4 on 2022-06-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newuser',
        ),
    ]
