# Generated by Django 4.0.4 on 2022-06-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_delete_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicinecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinecategory', models.CharField(max_length=50)),
            ],
        ),
    ]
