# Generated by Django 4.0.4 on 2022-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_medicinecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminemail', models.EmailField(max_length=50, unique=True)),
                ('adminpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
