# Generated by Django 4.0.4 on 2022-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('Logo', models.FileField(upload_to='uploads/wizardlogo/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
