# Generated by Django 4.0.4 on 2022-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_wizards'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizards',
            name='details',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wizards',
            name='license',
            field=models.FileField(null=True, upload_to='uploads/wizardlicense/'),
        ),
    ]
