# Generated by Django 4.0.4 on 2022-07-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_wizards_details_wizards_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizards',
            name='license',
            field=models.FileField(upload_to='uploads/wizardlicense/'),
        ),
    ]
