# Generated by Django 4.0.4 on 2022-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_wizards_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads/Adminimage/'),
        ),
    ]
