# Generated by Django 4.0.4 on 2022-07-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_adminlogin_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='photo',
        ),
    ]
