# Generated by Django 4.0.4 on 2022-06-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_medicinecategory'),
        ('TillageWizards', '0002_rename_newproduct_newmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmedicine',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.medicinecategory'),
        ),
    ]
