# Generated by Django 4.0.4 on 2022-06-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_newdeigner'),
        ('TillageWizards', '0005_rename_feedback_feedbackshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaintshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('attachment', models.ImageField(upload_to='uploads/complaintshopimages/')),
                ('vstatus', models.IntegerField(default=False)),
                ('replay', models.TextField(max_length=100)),
                ('doc', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
