# Generated by Django 4.0.4 on 2022-06-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_newdeigner'),
        ('TillageWizards', '0006_complaintshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintshop',
            name='user',
        ),
        migrations.AddField(
            model_name='complaintshop',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop'),
        ),
    ]
