# Generated by Django 4.0.4 on 2022-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TillageWizards', '0007_remove_complaintshop_user_complaintshop_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintshop',
            name='attachment',
            field=models.FileField(upload_to='uploads/complaintshopimages/'),
        ),
        migrations.AlterField(
            model_name='complaintshop',
            name='replay',
            field=models.TextField(default='noreply', max_length=100),
        ),
    ]
