# Generated by Django 4.0.4 on 2022-06-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0004_newdeigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=80)),
                ('logo', models.FileField(upload_to='uploads/serviceimages/')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newdeigner')),
            ],
        ),
    ]
