# Generated by Django 4.0.4 on 2022-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mname',
            name='stk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
