# Generated by Django 4.0.4 on 2022-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0004_rename_mname_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='con',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='em',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
