# Generated by Django 4.0.4 on 2022-06-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_newdeigner'),
        ('Designer', '0008_complaintdesigner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintdesigner',
            name='user',
        ),
        migrations.AddField(
            model_name='complaintdesigner',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newdeigner'),
        ),
    ]
