# Generated by Django 4.0.4 on 2022-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0009_remove_complaintdesigner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdesigner',
            name='attachment',
            field=models.FileField(upload_to='uploads/complaintimages/'),
        ),
        migrations.AlterField(
            model_name='complaintdesigner',
            name='replay',
            field=models.TextField(default='noreply', max_length=100),
        ),
    ]
