# Generated by Django 4.0.4 on 2022-06-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_delete_newuser'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='doj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='vstatus',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Newshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='uploads/shopimages/')),
                ('proof', models.FileField(upload_to='uploads/shopproof/')),
                ('doj', models.DateField(auto_now_add=True)),
                ('vstatus', models.IntegerField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
