# Generated by Django 4.0.4 on 2022-06-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_newuser_doj_newuser_vstatus_newshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='newshop',
            name='ownercontact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newshop',
            name='owneremail',
            field=models.EmailField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='newshop',
            name='ownername',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newshop',
            name='doj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newshop',
            name='logo',
            field=models.FileField(null=True, upload_to='uploads/shopimages/'),
        ),
        migrations.AlterField(
            model_name='newshop',
            name='proof',
            field=models.FileField(null=True, upload_to='uploads/shopproof/'),
        ),
        migrations.AlterField(
            model_name='newshop',
            name='vstatus',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
