# Generated by Django 4.0.4 on 2022-06-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_delete_newuser'),
        ('Guest', '0003_newshop_ownercontact_newshop_owneremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newdeigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='uploads/shopdesigner/')),
                ('proof', models.FileField(upload_to='uploads/designerproof/')),
                ('doj', models.DateField(auto_now_add=True)),
                ('vstatus', models.IntegerField(default=False)),
                ('wstatus', models.IntegerField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
