# Generated by Django 4.0.4 on 2022-06-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0004_newdeigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=80)),
                ('stock', models.IntegerField(max_length=50)),
                ('photo', models.ImageField(upload_to='uploads/productimages/')),
                ('doj', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
