# Generated by Django 4.0.4 on 2022-06-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
