# Generated by Django 4.0.4 on 2022-06-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_newdeigner'),
        ('User', '0003_newproduct_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(max_length=50)),
                ('shipment', models.IntegerField(max_length=50)),
                ('totalprice', models.IntegerField(max_length=50)),
                ('vstatus', models.IntegerField(default=False)),
                ('pstatus', models.IntegerField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.newproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
