# Generated by Django 4.0.4 on 2022-06-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_newdeigner'),
        ('User', '0004_bookproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookproduct',
            old_name='doj',
            new_name='bod',
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='shipment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='totalprice',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Bookmedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('shipment', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('vstatus', models.IntegerField(default=False)),
                ('pstatus', models.IntegerField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.newproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
    ]
