# Generated by Django 4.0.4 on 2022-06-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TillageWizards', '0003_newmedicine_cat'),
        ('User', '0005_rename_doj_bookproduct_bod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedicine',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TillageWizards.newmedicine'),
        ),
    ]
