# Generated by Django 4.0.4 on 2022-06-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_product_bookmedicine_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedicine',
            name='shipment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
