# Generated by Django 4.0.4 on 2022-06-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_bookmedicine_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmedicine',
            name='delivering',
            field=models.CharField(default='Not', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookproduct',
            name='delivering',
            field=models.CharField(default='Not', max_length=50, null=True),
        ),
    ]
