# Generated by Django 4.0.4 on 2022-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='consulationfee',
            field=models.IntegerField(default=False),
        ),
    ]
