# Generated by Django 4.0.4 on 2022-06-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_complaintuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintuser',
            name='attachment',
            field=models.FileField(upload_to='uploads/complaintuserimages/'),
        ),
    ]
