# Generated by Django 4.0.4 on 2022-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_complaintuser_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintuser',
            name='replay',
            field=models.TextField(default='noreply', max_length=100),
        ),
    ]
