# Generated by Django 4.0.4 on 2022-06-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_newdeigner'),
        ('User', '0016_alter_complaintuser_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaintusertoshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('attachment', models.FileField(upload_to='uploads/complaintusertoshopimages/')),
                ('vstatus', models.IntegerField(default=False)),
                ('replay', models.TextField(default='noreply', max_length=100)),
                ('doc', models.DateField(auto_now_add=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Complaintusertodesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('attachment', models.FileField(upload_to='uploads/complaintusertodesignerimages/')),
                ('vstatus', models.IntegerField(default=False)),
                ('replay', models.TextField(default='noreply', max_length=100)),
                ('doc', models.DateField(auto_now_add=True)),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newdeigner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Complaintproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('image', models.FileField(upload_to='uploads/complaintproductimages/')),
                ('vstatus', models.IntegerField(default=False)),
                ('replay', models.TextField(default='noreply', max_length=100)),
                ('doc', models.DateField(auto_now_add=True)),
                ('fromuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='Guest.newuser')),
                ('touser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='Guest.newuser')),
            ],
        ),
    ]
