# Generated by Django 4.0.4 on 2022-06-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_complaintusertoshop_complaintusertodesigner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintproduct',
            old_name='image',
            new_name='attachment',
        ),
    ]
