# Generated by Django 4.0.4 on 2022-06-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_rename_image_complaintproduct_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintusertoshop',
            name='shop',
        ),
    ]
