# Generated by Django 4.0.4 on 2022-07-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_newdeigner'),
        ('User', '0020_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.newshop'),
        ),
    ]
