# Generated by Django 4.0.4 on 2022-07-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_wizards_license'),
        ('User', '0021_help_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='shop',
        ),
        migrations.AddField(
            model_name='help',
            name='wizard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.wizards'),
        ),
    ]
