# Generated by Django 4.0.4 on 2022-07-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_remove_adminlogin_photo'),
        ('User', '0022_remove_help_shop_help_wizard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='from_shop',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='to_shop',
        ),
        migrations.AddField(
            model_name='chat',
            name='from_wizards',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_wizards', to='Admin.wizards'),
        ),
        migrations.AddField(
            model_name='chat',
            name='to_wizards',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_wizards', to='Admin.wizards'),
        ),
    ]
