# Generated by Django 4.0.4 on 2022-07-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_bookmedicine_dstatus_bookproduct_dstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='details',
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='totalprice',
            field=models.FloatField(),
        ),
    ]
